apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: psqlbranches.hops.ops.com.ai
spec:
  compositeTypeRef:
    apiVersion: hops.ops.com.ai/v1alpha1
    kind: PSQLBranch
  mode: Pipeline
  pipeline:
  - functionRef:
      name: hops-ops-psql-stackbranch
    step: branch
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
