apiVersion: hops.ops.com.ai/v1alpha1
kind: PSQLStack
metadata:
  name: psql
  namespace: default
spec:
  clusterName: production-cluster
  namespace: stackgres
  labels:
    team: platform
  nodePool:
    enabled: true
  storageClass:
    create: true
    name: psql
  stackgresOperator:
    values:
      deploy:
        restapi: true
  atlasOperator:
    values:
      prewarmDevDB: true
